version: '3.8'
services:
  slack-call:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: slack-produccion
    image: slack-call:1.0
    env_file:
      - envProduccion/.env
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 250M
        reservations:
          cpus: '0.10'
          memory: 100M
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: example
      #POSTGRES_PASSWORD
      #POSTGRES_USER
      #POSTGRES_DB
      

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080